"""Reconstruct all shots generated by :mod:`build_shot_dataset2`.

The input directory contains one seismic patch NPY file per shot and the aux
directory contains the matching metadata NPZ file.  Matching is done by the
file stem, for example ``patches_0001.npy`` is matched with
``patches_0001.npz``.
"""

import argparse
import os
from concurrent.futures import ThreadPoolExecutor, as_completed
from pathlib import Path

import numpy as np

from old_codes.recon_shot2 import load_metadata, load_patches


def reconstruct_from_patches(patches, positions, original_shape):
    """Reconstruct with the same Gaussian blending used by NumpyPatchProcessor."""
    if patches.ndim != 3:
        raise ValueError(f"Expected patches with shape [N,H,W], got {patches.shape}.")
    positions = np.asarray(positions, dtype=np.int64)
    if positions.ndim != 2 or positions.shape[1] != 2:
        raise ValueError("positions must have shape [num_patches, 2].")
    if positions.shape[0] != patches.shape[0]:
        raise ValueError("positions length must match the number of patches.")

    height, width = (int(value) for value in original_shape)
    _, patch_height, patch_width = patches.shape
    y = np.linspace(-1, 1, patch_height)
    x = np.linspace(-1, 1, patch_width)
    xv, yv = np.meshgrid(x, y)
    weight_patch = np.exp(-(xv ** 2 + yv ** 2) / (2 * 0.5 ** 2)).astype(np.float32)
    weight_patch /= weight_patch.max()

    reconstructed = np.zeros((height, width), dtype=np.float32)
    weight_sum = np.zeros((height, width), dtype=np.float32)
    for patch, (top, left) in zip(patches, positions):
        bottom = min(top + patch_height, height)
        right = min(left + patch_width, width)
        valid_height = bottom - top
        valid_width = right - left
        if valid_height <= 0 or valid_width <= 0:
            raise ValueError(f"Patch position {(top, left)} is outside {original_shape}.")
        weights = weight_patch[:valid_height, :valid_width]
        reconstructed[top:bottom, left:right] += patch[:valid_height, :valid_width] * weights
        weight_sum[top:bottom, left:right] += weights

    weight_sum[weight_sum == 0] = 1.0
    return reconstructed / weight_sum


def build_parser():
    parser = argparse.ArgumentParser(
        description=(
            "Reconstruct one output NPY file per shot from patch NPY files "
            "and matching aux NPZ metadata."
        ),
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    parser.add_argument(
        "--input_dir", "--input", dest="input_dir", required=True,
        help="Directory containing seismic patch NPY files.",
    )
    parser.add_argument(
        "--input_aux_dir", "--aux_dir", "--aux", dest="input_aux_dir", required=True,
        help="Directory containing matching aux metadata NPZ files.",
    )
    parser.add_argument(
        "--output_dir", "--output", dest="output_dir", required=True,
        help="Directory for reconstructed per-shot NPY files.",
    )
    parser.add_argument(
        "--workers", type=int, default=None,
        help="Number of reconstruction threads. Defaults to a reasonable CPU-based value.",
    )
    parser.add_argument(
        "--clip", nargs=2, type=float, default=None, metavar=("VMIN", "VMAX"),
        help="Clip each final reconstructed shot to [VMIN, VMAX].",
    )
    parser.add_argument(
        "--no_scale", action="store_true",
        help="Do not multiply patches by global_scale from the aux metadata.",
    )
    return parser


def _files_by_stem(directory, suffix):
    path = Path(directory)
    if not path.is_dir():
        raise FileNotFoundError(f"Directory does not exist: {path}")

    files = sorted(path.glob(f"*{suffix}"))
    by_stem = {}
    for file_path in files:
        if file_path.stem in by_stem:
            raise ValueError(
                f"Duplicate file stem {file_path.stem!r} in {path}: "
                f"{by_stem[file_path.stem]} and {file_path}"
            )
        by_stem[file_path.stem] = file_path
    return by_stem


def match_shots(input_dir, aux_dir):
    """Return exact ``(stem, patch_path, aux_path)`` matches or raise early."""
    patches = _files_by_stem(input_dir, ".npy")
    aux = _files_by_stem(aux_dir, ".npz")

    patch_stems = set(patches)
    aux_stems = set(aux)
    missing_aux = sorted(patch_stems - aux_stems)
    missing_patches = sorted(aux_stems - patch_stems)
    if missing_aux or missing_patches:
        details = []
        if missing_aux:
            details.append(
                f"missing aux for {len(missing_aux)} input file(s): "
                + ", ".join(missing_aux[:10])
            )
        if missing_patches:
            details.append(
                f"missing input for {len(missing_patches)} aux file(s): "
                + ", ".join(missing_patches[:10])
            )
        suffix = " ..." if len(missing_aux) > 10 or len(missing_patches) > 10 else ""
        raise ValueError("Input/aux files do not match exactly: " + "; ".join(details) + suffix)

    if not patches:
        raise ValueError(f"No .npy patch files found in {input_dir}")

    return [(stem, patches[stem], aux[stem]) for stem in sorted(patches)]


def reconstruct_one(stem, patch_path, aux_path, output_dir, no_scale, clip_range):
    patches = load_patches(patch_path)
    positions, original_shape, global_scale = load_metadata(
        aux_path, patches.shape[0]
    )
    if no_scale:
        scale = 1.0
    else:
        if global_scale is None:
            raise KeyError(
                f"Metadata {aux_path} does not contain `global_scale`; "
                "use --no_scale if the patches are already unscaled."
            )
        scale = global_scale

    reconstructed = reconstruct_from_patches(
        patches * scale, positions, original_shape
    ).astype(np.float32, copy=False)
    if clip_range is not None:
        reconstructed = np.clip(
            reconstructed,
            clip_range[0],
            clip_range[1],
        ).astype(np.float32, copy=False)
    output_path = Path(output_dir) / f"{stem}.npy"
    np.save(output_path, reconstructed)
    return output_path, reconstructed.shape


def reconstruct_dataset(args):
    if args.workers is not None and args.workers <= 0:
        raise ValueError("--workers must be positive.")
    if args.clip is not None and args.clip[0] > args.clip[1]:
        raise ValueError("--clip VMIN must be less than or equal to VMAX.")

    matches = match_shots(args.input_dir, args.input_aux_dir)
    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    workers = args.workers or min(32, (os.cpu_count() or 1) + 4)
    print(f"Matched shots: {len(matches)}, workers: {workers}")

    futures = {}
    with ThreadPoolExecutor(max_workers=workers) as executor:
        for stem, patch_path, aux_path in matches:
            future = executor.submit(
                reconstruct_one,
                stem,
                patch_path,
                aux_path,
                output_dir,
                args.no_scale,
                args.clip,
            )
            futures[future] = stem

        failed_stem = None
        try:
            for index, future in enumerate(as_completed(futures), start=1):
                failed_stem = futures[future]
                output_path, shape = future.result()
                print(f"[{index}/{len(matches)}] Saved {output_path} shape={shape}")
        except Exception as exc:
            for future in futures:
                future.cancel()
            raise RuntimeError(f"Shot reconstruction failed: {failed_stem}") from exc


if __name__ == "__main__":
    reconstruct_dataset(build_parser().parse_args())
