"""Reconstruct a seismic shot from BuildShotDataset2 patch files."""

import argparse
from pathlib import Path

import numpy as np


def build_parser():
    parser = argparse.ArgumentParser(
        description=(
            "Reconstruct one seismic shot from patch NPY data and the compact "
            "aux NPZ metadata generated by BuildShotDataset2.py."
        ),
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    parser.add_argument("--patches", required=True, help="Seismic patch NPY file.")
    parser.add_argument("--metadata", required=True, help="Patch aux NPZ file.")
    parser.add_argument("--output", required=True, help="Output reconstructed NPY file.")
    parser.add_argument(
        "--no_scale",
        action="store_true",
        help="Do not multiply the reconstructed normalized data by global_scale.",
    )
    return parser


def load_patches(path):
    patches = np.load(path)
    if patches.ndim == 4:
        if patches.shape[1] != 1:
            raise ValueError(
                f"Expected seismic patches with one channel, got shape {patches.shape}."
            )
        patches = patches[:, 0]
    if patches.ndim != 3:
        raise ValueError(
            f"Expected seismic patches with shape [N,H,W] or [N,1,H,W], got {patches.shape}."
        )
    return patches.astype(np.float32, copy=False)


def load_metadata(path, num_patches):
    with np.load(path) as metadata:
        required = {"positions", "original_shape"}
        missing = required.difference(metadata.files)
        if missing:
            raise KeyError(f"Metadata is missing required fields: {sorted(missing)}")

        positions = metadata["positions"].astype(np.int64, copy=False)
        original_shape = tuple(metadata["original_shape"].astype(np.int64).tolist())
        global_scale = None
        if "global_scale" in metadata.files:
            global_scale = float(np.asarray(metadata["global_scale"]).reshape(()))

    if positions.ndim != 2 or positions.shape[1] != 2:
        raise ValueError(f"positions must have shape [N,2], got {positions.shape}.")
    if len(original_shape) != 2:
        raise ValueError(f"original_shape must have two values, got {original_shape}.")
    if positions.shape[0] != num_patches:
        raise ValueError(
            f"positions length {positions.shape[0]} does not match patch count {num_patches}."
        )

    return positions, original_shape, global_scale


def reconstruct_from_patches(patches, positions, original_shape):
    from core.patching import NumpyPatchProcessor

    return NumpyPatchProcessor().reconstruct_from_overlapping_patches_2d(
        patches,
        positions,
        original_shape,
    )


def main():
    args = build_parser().parse_args()
    patches = load_patches(args.patches)
    positions, original_shape, global_scale = load_metadata(
        args.metadata,
        patches.shape[0],
    )

    if not args.no_scale:
        if global_scale is None:
            raise KeyError(
                "Metadata does not contain `global_scale`; use --no_scale if the "
                "patches are already in the desired amplitude scale."
            )
        patches = patches * global_scale

    reconstructed = reconstruct_from_patches(
        patches,
        positions,
        original_shape,
    ).astype(np.float32, copy=False)

    output_path = Path(args.output)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    np.save(output_path, reconstructed)
    scale_text = "disabled" if args.no_scale else f"{global_scale:.7g}"
    print(
        f"Saved reconstructed shot to {output_path} "
        f"shape={reconstructed.shape}, global_scale={scale_text}, "
        f"min={float(reconstructed.min()):.7g}, "
        f"max={float(reconstructed.max()):.7g}"
    )


if __name__ == "__main__":
    main()
